run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -236,26 +236,22 @@ jobs:
   run-migrations:
     docker:
       # Docker image here that supports NodeJS
-      - image: circleci/node:13.8.0
+      # - image: circleci/node:13.8.0
+      # - image: python:3.9-bullseye
+      # - image: python:3.10-alpine3.16
+      - image: python:3.11-rc-alpine
     steps:
       # Checkout code from git
       - checkout
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: Installing Dependencies
+          name: Install dependencies
           command: |
-            sudo apt install curl
-            sudo apt install unzip
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-            # sudo apt-get install -y npm
+            apk add --update --no-cache tar gzip nodejs npm aws-cli curl
       - run:
           name: Run migrations
           command: |
-            # Your code here
-
             export TYPEORM_HOST=$(aws cloudformation list-exports --query "Exports[?Name==\`EndpointAddress-${CIRCLE_WORKFLOW_ID:0:7}\`].Value" --output text)
             echo $TYPEORM_HOST
             echo TYPEORM_HOST=$TYPEORM_HOST >> ~/project/backend/.env
@@ -266,24 +262,84 @@ jobs:
             cat migrations_dump.txt
             # cd backend
             # npm install
-            # ## Run and save the migration output
+            # # Run and save the migration output
             # npm run migrations > migrations_dump.txt
-            # exit 1
+            
+            # # cat ~/project/backend/migrations_dump.txt
+
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/backend
       - run:
-          name: Send migration results to kvdb.io
+          name: Send migration results to memstash
           command: |
             # Your code here
-            echo "Contents of migrations_dump.txt: "
-            cat ~/project/backend/migrations_dump.txt
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-                  # using kvdb.io
-                  # curl -k https://kvdb.io/3F7kRvg2JNu6tZkt1yrqV2/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-                  curl -k https://kvdb.io/DG6z5ZtedjGhBEiEM83Z5o/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-            fi
             # exit 1
+            if grep -q "No migrations are pending" ~/project/backend/migrations_dump.txt
+            then
+              # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                curl https://kvdb.io/DG6z5ZtedjGhBEiEM83Z5o/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+      - run:  curl --insecure https://kvdb.io/DG6z5ZtedjGhBEiEM83Z5o/migration_${CIRCLE_WORKFLOW_ID:0:7}     
+      # - destroy_environments:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
      # Here's where you will add some code to rollback on failure  
-      # - destroy-environment
+
+
+  # run-migrations:
+  #   docker:
+  #     # Docker image here that supports NodeJS
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-build]
+  #     - run:
+  #         name: Installing Dependencies
+  #         command: |
+  #           sudo apt install curl
+  #           sudo apt install unzip
+  #           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+  #           unzip awscliv2.zip
+  #           sudo ./aws/install
+  #           # sudo apt-get install -y npm
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           # Your code here
+
+  #           export TYPEORM_HOST=$(aws cloudformation list-exports --query "Exports[?Name==\`EndpointAddress-${CIRCLE_WORKFLOW_ID:0:7}\`].Value" --output text)
+  #           echo $TYPEORM_HOST
+  #           echo TYPEORM_HOST=$TYPEORM_HOST >> ~/project/backend/.env
+  #           cd backend
+  #           npm install > /dev/null
+  #           npm run build > /dev/null
+  #           npm run migrations >> migrations_dump.txt
+  #           cat migrations_dump.txt
+  #           # cd backend
+  #           # npm install
+    #         # ## Run and save the migration output
+    #         # npm run migrations > migrations_dump.txt
+    #         # exit 1
+    #   - run:
+    #       name: Send migration results to kvdb.io
+    #       command: |
+    #         # Your code here
+    #         echo "Contents of migrations_dump.txt: "
+    #         cat ~/project/backend/migrations_dump.txt
+    #         if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+    #         then
+    #               # using kvdb.io
+    #               # curl -k https://kvdb.io/3F7kRvg2JNu6tZkt1yrqV2/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+    #               curl -k https://kvdb.io/DG6z5ZtedjGhBEiEM83Z5o/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+    #         fi
+    #         # exit 1
+    #  # Here's where you will add some code to rollback on failure  
+    #   # - destroy-environment
 
   deploy-frontend:
     docker:
